
services:
  laravel:
    build: .
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: nginx_laravel
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
